name = "Development"

[[data]]
name = "Rust (mise)"
description = "Installs the latest stable Rust toolchain via mise and adds rustfmt and clippy."
script = "rust.sh"
task_list = "I"

[[data]]
name = "Go (mise)"
description = "Installs the latest stable Go via mise."
script = "go.sh"
task_list = "I"

[[data]]
name = "Node.js (mise)"
description = "Installs the latest Node.js via mise and enables Corepack (Yarn/pnpm)."
script = "node.sh"
task_list = "I"

[[data]]
name = "Zig (mise)"
description = "Installs the latest stable Zig via mise."
script = "zig.sh"
task_list = "I"

[[data]]
name = "Java (mise)"
description = "Installs OpenJDK (prefers 21, falls back to 17) via mise."
script = "java.sh"
task_list = "I"

[[data]]
name = "Ruby (mise)"
description = "Installs the latest stable Ruby via mise."
script = "ruby.sh"
task_list = "I"


