name = "Applications Setup"

[[data]]
name = "Chris Titus Tech Windows Utility"
description = "Invokes Chris Titus Tech's Windows Utility directly from URL"
script = "chris-titus-utility.ps1"
task_list = "I"

[[data]]
name = "Nord Backgrounds"
description = "Downloads and extracts Nord theme backgrounds to Documents folder"
script = "nord-backgrounds.ps1"
task_list = "I" 