name = "System Setup"

[[data]]
name = "Update System"
description = "Updates the package database, upgrades all packages, and updates the ports tree."
script = "update-system.sh"
task_list = "I"

[[data]]
name = "Profile Setup"
description = "Sets up custom shell profile with fastfetch, starship, zoxide, and other utilities."
script = "profile-setup.sh"
task_list = "I"

[[data]]
name = "FreeBSD Upgrade"
description = "Manages FreeBSD version upgrades and package repository switching."
script = "freebsd-upgrade.sh"
task_list = "I"

[[data]]
name = "Ports Setup"
description = "Sets up the FreeBSD Ports Collection with git-based management."
script = "ports.sh"
task_list = "I"