name: Bug Report
description: Report a bug or issue with OSUtil.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Linux Distribution (if applicable)
      description: Only fill this out if you selected Linux above.
      placeholder: e.g., Ubuntu, Arch, Fedora
  - type: textarea
    id: issue
    attributes:
      label: Describe the issue
      description: What happened? Please provide details.
      placeholder: What went wrong?
    validations:
      required: true
