blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Jaredy899/osutil/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/Jaredy899/osutil#readme
    about: Check the README and documentation for help.
  - name: Multi-Platform Setup Guide
    url: https://github.com/Jaredy899/osutil/blob/main/MULTI_PLATFORM_SETUP.md
    about: Check the multi-platform setup guide for development help. 