name: Feature Request
description: Suggest a new feature or improvement for OSUtil.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Target Operating System
      options:
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe your feature or improvement
      description: What would you like to see added or changed?
      placeholder: Describe your idea here.
    validations:
      required: true
