name = "Windows Utilities"

[[data]]
name = "Chris Titus Tech Windows Utility"
description = "Invokes Chris Titus Tech's Windows Utility directly from URL"
script = "chris-titus-utility.ps1"
task_list = "I"

[[data]]
name = "Nord Backgrounds"
description = "Downloads and extracts Nord theme backgrounds to Documents folder"
script = "nord-backgrounds.ps1"
task_list = "I"

[[data]]
name = "Remote & SSH Setup"
description = "Core Windows system setup including remote desktop, SSH, and firewall configuration"
script = "remote-ssh-setup.ps1"
task_list = "I"

[[data]]
name = "Password Setup"
description = "Interactive password change utility for the currently logged-in user"
script = "password-setup.ps1"
task_list = "I"

[[data]]
name = "Time Setup"
description = "Automatic timezone detection and time synchronization configuration"
script = "time-setup.ps1"
task_list = "I"

[[data]]
name = "PowerShell Setup"
description = "Downloads and installs development tools, fonts, profiles, and configurations for PowerShell"
script = "powershell-setup.ps1"
task_list = "I"

[[data]]
name = "Update Windows"
description = "This script updates Windows"
script = "update.ps1"
task_list = "I"

[[data]]
name = "Windows Activation"
description = "Activates Windows using the get.activated.win service"
script = "windows-activation.ps1"
task_list = "I"

[[data]]
name = "SSH Key Manager"
description = "Interactive tool to manage SSH keys for Windows administrators, including GitHub import and manual entry"
script = "ssh-key-manager.ps1"
task_list = "I"

[[data]]
name = "First Setup"
description = "Initial Windows system setup and configuration"
script = "first-setup.ps1"
task_list = "I" 