name = "Security"

[[data.preconditions]]
matches = false
data = "command_exists"
values = ["pkg"]

[[data]]
name = "UFW Firewall Baselines (CTT)"
description = "Developed to ease iptables firewall configuration, UFW provides a user friendly way to create an IPv4 or IPv6 host-based firewall. This command installs UFW and configures UFW based on CTT's recommended rules. For more information visit: https://christitus.com/linux-security-mistakes"
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "dnf", "zypper", "apk" ]

[[data]]
name = "UFW Docker Integration"
description = "Fixes the Docker and UFW security flaw by properly integrating Docker with UFW firewall rules. This allows you to control access to Docker containers through UFW without disabling iptables. For more information visit: https://github.com/chaifeng/ufw-docker"
script = "ufw-docker-setup.sh"
task_list = "I SS"

[[data.preconditions]]
matches = true
data = "command_exists"
values = [ "docker" ]

[[data]]
name = "FirewallD Firewall Baselines (CTT)"
description = "Configure FirewallD with CTT's recommended baseline rules for improved system security. For more information visit: https://christitus.com/linux-security-mistakes"
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "apt-get", "nala", "pacman", "apk", "xbps-install", "eopkg" ]

[[data]]
name = "Tailscale"
description = "Tailscale is a zero-trust network overlay that utilizes the WireGuard protocol for secure connectivity across resources."
script = "tailscale.sh"
task_list = "I SS"

[[data]]
name = "iptables Firewall Baselines (CTT)"
description = "Applies CTT's recommended iptables firewall rules for Alpine Linux (apk). For more information visit: https://christitus.com/linux-security-mistakes"
script = "iptables.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "apt-get", "nala", "pacman", "dnf", "zypper", "xbps-install", "eopkg" ]
