name = "Security"

[[data]]
name = "UFW Firewall Baselines (CTT)"
description = "Developed to ease iptables firewall configuration, UFW provides a user friendly way to create an IPv4 or IPv6 host-based firewall. This command installs UFW and configures UFW based on CTT's recommended rules. For more information visit: https://christitus.com/linux-security-mistakes"
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "dnf", "zypper" ]

[[data]]
name = "FirewallD Firewall Baselines (CTT)"
description = "Configure FirewallD with CTT's recommended baseline rules for improved system security. For more information visit: https://christitus.com/linux-security-mistakes"
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "apt-get", "nala", "pacman", "apk", "xbps-install", "eopkg" ]

[[data]]
name = "Tailscale"
description = "Tailscale is a zero-trust network overlay that utilizes the WireGuard protocol for secure connectivity across resources."
script = "tailscale.sh"
task_list = "I SS"

[[data]]
name = "iptables Firewall Baselines (CTT)"
description = "Applies CTT's recommended iptables firewall rules for Alpine Linux (apk). For more information visit: https://christitus.com/linux-security-mistakes"
script = "iptables.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "apt-get", "nala", "pacman", "dnf", "zypper", "xbps-install", "eopkg" ]
