name = "Applications Setup"

[[data]]
name = "Firefox"
description = "Installs the Firefox web browser."
script = "firefox.sh"
task_list = "I"

[[data]]
name = "XFCE Desktop"
description = "Installs XFCE desktop environment with SLiM login manager."
script = "xfce.sh"
task_list = "I"

[[data]]
name = "Fix VM Mouse (Proxmox)"
description = "Fixes mouse issues in Proxmox VM environments with additional drivers and configuration."
script = "fix-vm-mouse.sh"
task_list = "I"
