name = "Applications Setup"

[[data]]
name = "Firefox"
description = "Installs the Firefox web browser."
script = "firefox.sh"
task_list = "I"

[[data]]
name = "XFCE Desktop"
description = "Installs XFCE desktop environment with SLiM login manager."
script = "xfce.sh"
task_list = "I"

[[data]]
name = "Fastfetch"
description = "Installs and configures Fastfetch system information tool."
script = "fastfetch-setup.sh"
task_list = "I"

